global:
  scrape_interval: 15s 
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]


  - job_name: "node" 
    static_configs: 
    - targets: ["node-exporter:9100"]

  # - job_name: 'docker'
  #   dockerswarm_sd_configs:
  #     - host: unix:///var/run/docker.sock
  #       role: nodes
  #   relabel_configs:
  #     # Fetch metrics on port 9323.
  #     - source_labels: [__meta_dockerswarm_node_address]
  #       target_label: __address__
  #       replacement: $1:9323
  #     # Set hostname as instance label
  #     - source_labels: [__meta_dockerswarm_node_hostname]
  #       target_label: instance


  - job_name: loginapp
    # metrics_path: /metrics
    static_configs:
      - targets: ['app:8000']